name: Build and Push Docker Image

on: [push, pull_request]

env:
  REGISTRY: ${{ vars.DOCKER_REGISTRY }} # e.g. registry.example.com
  IMAGE_NAME: ssh-deluge-companion
  CACHE_IMAGE: "${{ vars.DOCKER_REGISTRY }}/ssh-deluge-companion:cache"
  FULL_IMAGE_NAME: "${{ vars.DOCKER_REGISTRY }}/ssh-deluge-companion"
jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    steps:
      - name: debug env vars
        run: echo "${{ toJson(env) }}"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to private registry
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ secrets.NAS_REGISTRY_USER }}
          password: ${{ secrets.NAS_REGISTRY_PASSWD }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: "${{ env.FULL_IMAGE_NAME }}"
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=sha,format=short

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # cache-from: type=registry,ref=${{ env.CACHE_IMAGE }}
          # cache-to: type=registry,ref=${{ env.CACHE_IMAGE }},mode=max
