name: Build and Push Docker Image

on: [push, pull_request]

env:
  REGISTRY: ghcr.io # GitHub Container Registry
  IMAGE_NAME: ${{ vars.PROJECT_NAME || 'ssh_tcp_proxy' }}
  FULL_IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/${{ vars.PROJECT_NAME || 'ssh_tcp_proxy' }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.FULL_IMAGE_NAME }}
          flavor: |
            latest=${{ vars.USE_LATEST_TAG || 'false' }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=sha,format=short

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
